# ***WELCOME***


In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5], np.int64) ##creating a 64bit array

In [3]:
a


array([1, 2, 3, 4, 5], dtype=int64)

In [4]:
a[4]##accessing array elements

5

In [5]:
a.shape##returns the (rows,colum)of an array


(5,)

In [6]:
a.dtype##describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted.

dtype('int64')

In [7]:
b = (1,2,3)
np.array(b)

array([1, 2, 3])

In [8]:
b

(1, 2, 3)

# Array creation : Conversion form other Python structures

In [9]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
zeros = np.zeros([2,3])

In [15]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
o = np.zeros((2,3))

In [17]:
o is zeros

False

In [18]:
np.arange(0,90)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [19]:
for n in np.arange(0,90):
    print(n)
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89


In [20]:
np.linspace(0,4,3)##equally linear space elemnts

array([0., 2., 4.])

In [21]:
np.empty((4,6))##return a new array of given shape and type, without initializing entries.

array([[2.37663529e-312, 2.29175545e-312, 2.33419537e-312,
        2.37663529e-312, 2.10077583e-312, 8.48798317e-313],
       [9.33678148e-313, 9.33678148e-313, 8.70018275e-313,
        7.42698527e-313, 2.39785524e-312, 2.05833592e-312],
       [2.29175545e-312, 6.79038654e-313, 2.22809558e-312,
        2.14321575e-312, 2.41907520e-312, 2.44029516e-312],
       [2.05833592e-312, 2.14321575e-312, 2.14321575e-312,
        2.14321575e-312, 2.33419537e-312, 2.44029516e-312]])

In [22]:
np.empty_like(a)##makes an empty array of the (given) array size

array([7956012744315465321, 8243102915232669812,  729618461982600819,
             2199562231840,                   0], dtype=int64)

In [23]:
np.identity(4)##gives (given x given ) number identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
##important
y = np.arange(99)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
y = y.reshape(3,33)

In [26]:
y.reshape(1,2)##not possible since array has 99 elements and 1 *2 is not 99

ValueError: cannot reshape array of size 99 into shape (1,2)

In [27]:
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [28]:
y = y.ravel()##returns a flattened array i.e., 1D array

In [29]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [31]:
x = np.array(x)

In [32]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [33]:
x.sum(axis=0) ##axis 0 is column 

array([12,  8,  9])

In [34]:
x.sum(0)

array([12,  8,  9])

In [35]:
x.sum(axis=1) ##axis 1 is rows

array([ 6, 15,  8])

In [36]:
x.sum(0)

array([12,  8,  9])

In [37]:
x.T ##transposes the original array(transpose = changes row to column ad vice - versa  )

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [38]:
 x.flat

In [39]:
for item in x.flat: ##prints all the elements in array x(original x initialized array)
    print(item)

1
2
3
4
5
6
7
1
0


In [41]:
x.ndim ##no of dimensions in an array


2

In [42]:
x.size ##totoal elements in x array

9

In [47]:
x.nbytes ##total bytes consumed

36

In [44]:
one = np.array([1,2,3,4,5,6])

In [45]:
one.argmax() ##it contains brackets therfore it is a function(argmax returns the index where the maximum value is present)

5

In [48]:
one.argmin()##Return indices of the minimum values

0

In [49]:
one.argsort()##Returns the indices that would sort this array.

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [51]:
one.sort()

In [52]:
one

array([1, 2, 3, 4, 5, 6])

In [55]:
x


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [57]:
x.argmin() ##first it flattens the 2d array then gives the minimum elemnt indix

8

In [59]:
x.argmax(0) #returns the index of the max element in the(sepcified axis)note : axis 0 is the columns

array([2, 1, 1], dtype=int64)

In [61]:
x.argsort(0) ##returns sorted elements suitable for sorted column

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [63]:
x.argsort() ##default axis is 1(sorted in rows manner)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [64]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
x.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
x.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [67]:
x.reshape(9,) 

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [69]:
y = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [72]:
x 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [74]:
x + y ##numpy allows matrix operation

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [76]:
x*y ##element with same indexes,axis are multiplied

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [78]:
np.sqrt(x) ##underroot of all the elements of (specified array)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [79]:
y

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [80]:
y.max()

8

In [81]:
y.min()

0

In [84]:
y.sum()


23

In [85]:
##finding elements in an array

In [87]:
y

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [97]:
np.where(y<2) 
#returns all the indexes of element of y<2 
#it returns 2 arrays[row indexes],[column indexes] 
#match that and you will get your required numbers





(array([0, 0, 1, 2, 2], dtype=int64), array([0, 2, 1, 1, 2], dtype=int64))

In [98]:
type(np.where(y<2)) ##returns tuple of an array

tuple

In [99]:
np.count_nonzero(y)

7

In [103]:
np.nonzero(y)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1], dtype=int64))

In [104]:
import sys

In [107]:
py_y = [0,4,55,2] ##normal list

In [109]:
arr_y = np.array(py_y)##array
arr_y


array([ 0,  4, 55,  2])

In [114]:
sys.getsizeof(1) * len(py_y) ##list takes 112 bytes

112

In [116]:
arr_y.itemsize*arr_y.size ##arrays only takes 16 bytes

16

In [117]:
#https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.html
#ALL Numpy methods and attributes official Documentation
